name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
        # cach
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
    # Instalar as dependências NPM/Yarn
    - name: Install dependencies
      run: yarn
    
    # Executar a build
    - name: Run build
      run: yarn build
    # Copiar pasta dist pra dentro da Digital Ocean 
    # Substituir o código existente na pasta "dist" pelo novo código
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/node-backend-go-barber"
  
    - name: select node
      uses: dcodeIO/setup-node-nvm@master
      with:
         node-version: lts/*
        
    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/node-backend-go-barber 
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-api
